#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1505813783 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: false
# https://www.clocked.me
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/temp-icon.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: "Clocked: Your Drag Queen Guide" # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: You've gotta Clock 'em all!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Matthew Smith
your_link: mailto:support@clocked.me
your_city: San Francisco
email_address: support@clocked.me
instagram_username: clocked_app
twitter_username: ClockedApp
facebook_username:
# github_username                           : emilbaehr
# youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Performers
    description: "Want to know more about your favorite drag queens? Detailed bios, social media info and more!"
    fontawesome_icon_name: crown

  - title: Favorites
    description: "Find your favorite drag performers."
    fontawesome_icon_name: heart

  - title: Clocked
    description: "Want to track which drag queens you’ve already seen? The app makes it easy to tack of your drag experiences."
    fontawesome_icon_name: stopwatch

  - title: Drag Race
    description: "What was that runway? Who won that challenge? Fast answers, detailed episode information."
    fontawesome_icon_name: flag-checkered

  - title: Spoiler Protection
    description: "Hide the winners and placement details for any season, all with the flick of your wrist, I mean flick of a switch."
    fontawesome_icon_name: eye-slash

  - title: Premium
    description: "Help support the app and future updates by going Premium! Ad-free and a bonus sticker pack included."
    fontawesome_icon_name: medal

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.2
topbar_title_color: "#ffffff"

cover_image: assets/background.jpg # Replace with alternative image path or image URL.
# cover_overlay_color: "#363b3d"
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.6

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#000000"

link_color: "#FF00AD"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#FFFFFF"
feature_text_color: "#e6e6e6"

feature_icons_foreground_color: "#FF00AD"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#FF00AD"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#e6e6e6"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
